# Minimal Read the Docs configuration
version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Python environment
python:
  install:
    - requirements: docs/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
