# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Set the version of Python and requirements required to build your docs
python:
  version: 3.10
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .


# Optionally build your docs in additional formats such as PDF
formats:
  - htmlzip

# Build documentation in the docs/ directory with Sphinx
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - python -m pip install --upgrade pip setuptools wheel
      - python -m pip install -e .
      - python -m pip install -r docs/requirements.txt
  - pdf
  - epub

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
