version: 2

build:
  os: ubuntu-22.04  # Using 22.04 for better compatibility
  tools:
    python: "3.10"  # Using Python 3.10 which is more stable with RTD

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Explicitly install the theme
formats: all
