# Configuration file for the Sphinx documentation builder.

# -- Project information -----------------------------------------------------
project = 'Gamma Delta Sense'
copyright = '2025, JurisGPT'
author = 'JurisGPT'
version = '1.0.0'
release = '1.0.0'

# The full version, including alpha/beta/rc tags
release = '1.0.0'

# -- General configuration ---------------------------------------------------
# Add any Sphinx extension module names here, as strings
# See https://www.sphinx-doc.org/en/master/usage/extensions/index.html
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The master toctree document.
master_doc = 'index'

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
source_encoding = 'utf-8-sig'

# The language for content autogenerated by Sphinx.
language = 'en'

# CRITICAL: Use built-in theme (NOT sphinx_rtd_theme)
html_theme = 'alabaster'
html_static_path = []

html_theme_options = {
    'description': 'Immunology Knowledge Base Development & Monitoring System',
    'github_user': 'jurisgpt',
    'github_repo': 'gamma_delta_sense',
    'github_banner': True,
    'show_powered_by': False,
}

html_show_sphinx = False
html_show_copyright = True

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
}
